name: "umom"
version: "3.8"

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=umomdb'
      - 'POSTGRES_PASSWORD=programmist67'
      - 'POSTGRES_USER=terentiy'
    ports:
      - '5432:5432'
    networks:
      - backend-network

  auth:
    image: quay.io/keycloak/keycloak:22.0.1
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --import-realm
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/opt/keycloak/data/import"
      - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
    volumes:
      - ./realms:/opt/keycloak/data/import
    networks:
      - backend-network

    restart: always

networks:
  backend-network: